### ISSUE TITLE
Peer review Mercado Liebre

### ISSUE THREAD

**Issue by pedroizanuttini** [lupish/mercadoLiebre#1]
Puntos a tener en cuenta:
1
Header, Main y Footer contiene todos los elementos en cada seccion.

2
-Footer: Para el caso del footer, la unica observacion son las leyendas que estan debajo de Paga con tarjeta o en efectivo. Envio Gratis y desde $2500. Deberia tener un poco mas de separacion entre ambas. (Esto solo para resolucion tablet y desktop)

3
El sitio se adapta a las distintas resoluciones de pantalla correctamente.

4
El sitio cuenta con formulario de registro de usuarios.

5
El sitio cuenta con un formulario de login.

6
Se muestran mensajes de error cuando la information es equivocada.

7
El search bar en un formulario.

8
Las animaciones y transiciones estan todas correctas. Una unica observacion(solo un pequena mejora), podrias aplicar el atributo transicion para que cuando se haga el hover sobre los productos transicion no sea tan brusca. Ej: transition: all 250ms ease-in-out.

9
El trabajo esta muy bien realizado. Excelente!!

10
Nada por mejorar. Cumple con todas las especificaciones.

**Comment by lupish** [comment]
Gracias por el peer review Pedro!
Agregué el margen en los íconos del footer, así queda ese espacio que comentabas
