### ISSUE TITLE
Peer Review-MercadoLiebre

### ISSUE THREAD

**Issue by sheine1234** [lupish/mercadoLiebre#2]
- [ ] 1- Cumple con todo lo solicitado.
- [ ] 2- Cumple ya que los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 píxeles. Respecto al contendio centrado, faltaría centrar el "Copyrigth".
- [ ] 3- Cumple con la consigna ya que el sitio se adapta a las distintas resoluciones de pantalla.
- [ ] 4- Cumple ya que el sitio cuenta con un formulario de registro de usuarios.
- [ ] 5- Cumple ya que el sitio cuenta con un formulario de login pero cambiaría el "Elegí tu contraseña" por un "Ingresá tu contraseña".
- [ ] 6- Cumple parcial porque el mensaje de error faltan en algunos campos.
- [ ] 7- Cumple ya que el search bar es un formulario.
- [ ] 8- Sí, se utilizan animaciones y propiedades de transición de CSS.
- [ ] 9- El sitio se adapta muy bien a las distintas resoluciones de pantalla.
- [ ] 10- Podría estar bueno mejorar en el diseño de los formularios y agergar el título del tipo de formulario, para que cuando unos se encuentra en el sitio, tener la posibilidad de ver claramente para qué estoy completando mi información.

**Comment by lupish** [comment]
Gracias por los comentarios Sheine!
Sobre el punto 2, estuve revisando y el Copyrigth no dice que debería ser centrado o al menos no lo encontré, pero sí le agregué un margen a la izquierda para que no quedara tan pegado al comienzo de la pantalla.
En cuanto al punto 10, hice unas mejoras a nivel diseño en los formularios y le agregué los títulos.
